---
swagger: "2.0"
info:
  description: "Swagger tutorial"
  version: "1.0.0"
  title: "Swagger tutorial"
basePath: "/service-api"
schemes:
- "http"
paths:
  /student:
    post:
      summary: "Add a new student"
      description: ""
      operationId: "add_student"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Student"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "integer"
            format: "int64"
        "405":
          description: "Invalid input"
        "409":
          description: "already exists"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /student/{student_id}:
    get:
      summary: "Find student by ID"
      description: "Returns a single student"
      operationId: "get_student_by_id"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to return"
        required: true
        type: "integer"
        format: "int64"
      - name: "subject"
        in: "query"
        description: "The subject name"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "student not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    delete:
      summary: "Delete student by ID"
      description: ""
      operationId: "delete_student"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "student_id"
        in: "path"
        description: "ID of student to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "student not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /student/:
    get:
      summary: "Find student by Last Name"
      description: "Returns a single student"
      operationId: "get_student_by_last_name"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "last_name"
        in: "query"
        description: "Last name of student to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        "400":
          description: "Invalid Last name supplied"
        "404":
          description: "student not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Student:
    type: "object"
    properties:
      student_id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
      grades:
        type: "object"
        properties: {}
    example:
      student_id: 0
      last_name: "last_name"
      grades: "{}"
      first_name: "first_name"
